/* Vocali — glossary. Terms are underlined inline in lesson text (first use per
   page) with the definition on hover, and listed A–Z on the Glossary page. */

export const glossary = {
  'passaggio': 'The transition zone between vocal registers where fold coordination must shift — the "break".',
  'twang': 'A bright, ringing resonance made by narrowing the space above the folds; adds carrying power without force.',
  'SOVT': 'Semi-occluded vocal tract exercises (lip trills, straws, hums) that balance the folds using gentle back-pressure.',
  'TA': 'Thyroarytenoid muscle — the body of the vocal fold; shortens and thickens it (chest-dominant).',
  'CT': 'Cricothyroid muscle — tilts the thyroid cartilage to stretch and thin the folds for higher pitch (head-dominant).',
  'onset': 'How a note begins — the way the folds come together at the very start of a tone.',
  'messa di voce': 'A sustained note taken softly to loud and back to soft on a single breath.',
  'formant': 'A resonance peak of the vocal tract that shapes vowel identity and tone colour.',
  'mix': 'A balanced blend of chest and head fold function that carries strength through the passaggio.',
  'registration': 'How the vocal folds change their vibration pattern across your range (chest, mix, head).',
  'larynx': 'The "voice box" that houses the vocal folds; its height strongly affects tone colour.',
  'falsetto': 'A light upper-register sound where the folds vibrate with a gap between them, giving a breathy tone.',
  'glottis': 'The opening between the two vocal folds.',
  'vibrato': 'A small, regular fluctuation of pitch that gives a sung note warmth and life.',
  'medial compression': 'How firmly the vocal folds press together along their length; too little is breathy, too much is pressed.',
  'appoggio': 'A balanced breath-support coordination that keeps the ribs expanded and the airflow steady.',
  'diaphragm': 'The dome of muscle below the lungs. It contracts downward to draw air in — it is an inhaling muscle and cannot push air out.',
  'subglottic pressure': 'Air pressure below the vocal folds. Steady pressure gives steady tone; surges and collapses are heard as wobble and drift.',
  'soft palate': 'The flexible tissue at the back of the roof of the mouth. Raised it seals off the nose; lowered it lets sound resonate there (nasality).',
  'velum': 'Another name for the soft palate.',
  'singer\'s formant': 'A concentration of energy around 2.8–3.2 kHz that makes a voice carry, because human hearing is most sensitive in that band.',
  'vocal tract': 'The tube above the vocal folds — pharynx, mouth and nose — whose shape filters the raw buzz into a recognisable voice.',
  'pharynx': 'The throat space directly above the larynx; a major contributor to tone colour.',
  'glottal onset': 'A note begun by closing the folds first and letting pressure blow them apart — heard as a small click.',
  'aspirate onset': 'A note begun with air flowing before the folds close — heard as a breathy "h" before the tone.',
  'balanced onset': 'A note where airflow and fold closure begin together — clean, efficient and the healthiest default.',
  'vowel modification': 'Slightly migrating a vowel towards a neighbouring one as pitch rises, so it keeps acoustic support instead of straining.',
  'melisma': 'Several notes sung on a single syllable — the technical basis of riffs and runs.',
  'pentatonic': 'A five-note scale; with the flattened fifth added it becomes the blues scale, the home of most jazz and blues ornament.',
  'flow phonation': 'The efficient balance of airflow and closure that produces the most sound for the least effort.',
  'stroboscopy': 'A clinical technique using flashing light to make vocal fold vibration appear slowed, so it can be observed.'
}
